export enum ActionTypes {
  UPDATE_ARTICLE = '[UPDATE_ARTICLE] UPDATE ARTICLE',
  UPDATE_ARTICLE_SUCCESS = '[UPDATE_ARTICLE_SUCCESS] UPDATE ARTICLE SUCCESS',
  UPDATE_ARTICLE_FAILURE = '[UPDATE_ARTICLE_FAILURE] UPDATE ARTICLE FAILURE',

  GET_ARTICLE = '[GET_ARTICLE] GET ARTICLE',
  GET_ARTICLE_SUCCESS = '[GET_ARTICLE_SUCCESS] GET ARTICLE SUCCESS',
  GET_ARTICLE_FAILURE = '[GET_ARTICLE_FAILURE] GET ARTICLE FAILURE',

  DELETE_ARTICLE = '[DELETE_ARTICLE] DELETE ARTICLE',
  DELETE_ARTICLE_SUCCESS = '[DELETE_ARTICLE_SUCCESS] DELETE ARTICLE SUCCESS',
  DELETE_ARTICLE_FAILURE = '[DELETE_ARTICLE_FAILURE] DELETE ARTICLE FAILURE',
}
