export enum ActionTypes {
  GET_ARTICLE = '[ARTICLE] GET ARTICLE',
  GET_ARTICLE_SUCCESS = '[ARTICLE] GET ARTICLE SUCCESS',
  GET_ARTICLE_FAILURE = '[ARTICLE] GET ARTICLE FAILURE',

  DELETE_ARTICLE = '[ARTICLE] DELETE ARTICLE',
  DELETE_ARTICLE_SUCCESS = '[ARTICLE] DELETE ARTICLE SUCCESS',
  DELETE_ARTICLE_FAILURE = '[ARTICLE] DELETE ARTICLE FAILURE',
}
