export enum ActionTypes {
  GET_POPULAR_TAGS = '[POPULAR_TAGS] GET POPULAR TAGS',
  GET_POPULAR_TAGS_SUCCESS = '[POPULAR_TAGS] GET POPULAR TAGS_SUCCESS',
  GET_POPULAR_TAGS_FAILURE = '[POPULAR_TAGS] GET POPULAR TAGS_FAILURE',
}
