export enum ActionTypes {
  CREATE_ARTICLE = '[CREATE_ARTICLE] CREATE ARTICLE',
  CREATE_ARTICLE_SUCCESS = '[CREATE_ARTICLE_SUCCESS] CREATE ARTICLE_SUCCESS',
  CREATE_ARTICLE_FAILURE = '[CREATE_ARTICLE_FAILURE] CREATE ARTICLE_FAILURE',
}
